// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0EEGvsTNcn94lY7R-QDgwWGWhz-IU7Zc',
    appId: '1:36684847155:web:5cd01967b60e904cdbeb46',
    messagingSenderId: '36684847155',
    projectId: 'aquarium-bleu',
    authDomain: 'aquarium-bleu.firebaseapp.com',
    storageBucket: 'aquarium-bleu.appspot.com',
    measurementId: 'G-2EH7VSFD8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUK9Creis-08pAJVdETjaCV19-7whC1_0',
    appId: '1:36684847155:android:795f08a5ec246b2fdbeb46',
    messagingSenderId: '36684847155',
    projectId: 'aquarium-bleu',
    storageBucket: 'aquarium-bleu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVaUUGPSDM5O-wN-Mk1aATGcyoJZQZAtA',
    appId: '1:36684847155:ios:89c4d88cb6212349dbeb46',
    messagingSenderId: '36684847155',
    projectId: 'aquarium-bleu',
    storageBucket: 'aquarium-bleu.appspot.com',
    iosClientId: '36684847155-jddi2pcpndjg36lg8kd9i4msjsi4ol5i.apps.googleusercontent.com',
    iosBundleId: 'com.aquariumBleu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVaUUGPSDM5O-wN-Mk1aATGcyoJZQZAtA',
    appId: '1:36684847155:ios:89c4d88cb6212349dbeb46',
    messagingSenderId: '36684847155',
    projectId: 'aquarium-bleu',
    storageBucket: 'aquarium-bleu.appspot.com',
    iosClientId: '36684847155-jddi2pcpndjg36lg8kd9i4msjsi4ol5i.apps.googleusercontent.com',
    iosBundleId: 'com.aquariumBleu',
  );
}
